default_thumbnail_mode:
  default: grid
  type: enum
  choices:
    - grid
    - list
    - none

list_categories:
  type: list
  list_type: category
  default: ""

grid_categories:
  type: list
  list_type: category
  default: ""

placeholder_icon:
  default: "comments"

mobile_thumbnails:
  default: true
