default_thumbnail_mode:
  default: grid
  type: enum
  choices:
    - grid
    - masonry
    - list
    - none

grid_categories:
  type: list
  list_type: category
  default: ""

masonry_categories:
  type: list
  list_type: category
  default: ""

list_categories:
  type: list
  list_type: category
  default: ""

grid_tags:
  type: list
  list_type: tag
  default: ""

masonry_tags:
  type: list
  list_type: tag
  default: ""

list_tags:
  type: list
  list_type: tag
  default: ""

placeholder_icon:
  default: "comments"

mobile_thumbnails:
  default: true
